# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inst_dep_record.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15inst_dep_record.proto\x12\x0cProtoMessage\"]\n\x13InstDepRecordHeader\x12\x0e\n\x06obj_id\x18\x01 \x02(\t\x12\x0e\n\x03ver\x18\x02 \x01(\r:\x01\x30\x12\x11\n\ttick_freq\x18\x03 \x02(\x04\x12\x13\n\x0bwindow_size\x18\x04 \x02(\r\"\xb6\x02\n\rInstDepRecord\x12\x0f\n\x07seq_num\x18\x01 \x02(\x04\x12=\n\x04type\x18\x02 \x02(\x0e\x32&.ProtoMessage.InstDepRecord.RecordType:\x07INVALID\x12\x0e\n\x06p_addr\x18\x03 \x01(\x04\x12\x0c\n\x04size\x18\x04 \x01(\r\x12\r\n\x05\x66lags\x18\x05 \x01(\r\x12\x0f\n\x07rob_dep\x18\x06 \x03(\x04\x12\x12\n\ncomp_delay\x18\x07 \x02(\x04\x12\x0f\n\x07reg_dep\x18\x08 \x03(\x04\x12\x0e\n\x06weight\x18\t \x01(\r\x12\n\n\x02pc\x18\n \x01(\x04\x12\x0e\n\x06v_addr\x18\x0b \x01(\x04\x12\x0c\n\x04\x61sid\x18\x0c \x01(\r\"8\n\nRecordType\x12\x0b\n\x07INVALID\x10\x00\x12\x08\n\x04LOAD\x10\x01\x12\t\n\x05STORE\x10\x02\x12\x08\n\x04\x43OMP\x10\x03')



_INSTDEPRECORDHEADER = DESCRIPTOR.message_types_by_name['InstDepRecordHeader']
_INSTDEPRECORD = DESCRIPTOR.message_types_by_name['InstDepRecord']
_INSTDEPRECORD_RECORDTYPE = _INSTDEPRECORD.enum_types_by_name['RecordType']
InstDepRecordHeader = _reflection.GeneratedProtocolMessageType('InstDepRecordHeader', (_message.Message,), {
  'DESCRIPTOR' : _INSTDEPRECORDHEADER,
  '__module__' : 'inst_dep_record_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMessage.InstDepRecordHeader)
  })
_sym_db.RegisterMessage(InstDepRecordHeader)

InstDepRecord = _reflection.GeneratedProtocolMessageType('InstDepRecord', (_message.Message,), {
  'DESCRIPTOR' : _INSTDEPRECORD,
  '__module__' : 'inst_dep_record_pb2'
  # @@protoc_insertion_point(class_scope:ProtoMessage.InstDepRecord)
  })
_sym_db.RegisterMessage(InstDepRecord)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSTDEPRECORDHEADER._serialized_start=39
  _INSTDEPRECORDHEADER._serialized_end=132
  _INSTDEPRECORD._serialized_start=135
  _INSTDEPRECORD._serialized_end=445
  _INSTDEPRECORD_RECORDTYPE._serialized_start=389
  _INSTDEPRECORD_RECORDTYPE._serialized_end=445
# @@protoc_insertion_point(module_scope)
